# Generated by Django 2.2 on 2019-05-21 04:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190521_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecolumn',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 4, 53, 51, 526900, tzinfo=utc)),
        ),
    ]
